services:
  db:
    image: postgres:14-alpine
    container_name: bug_db
    hostname: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - bug_pgdata:/var/lib/postgresql/data
    ports: 
      - ${DB_PORT_FORWARD}:${DB_PORT}
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_PORT_FORWARD}:${PG_PORT}

  redis: 
    image: redis/redis-stack:latest
    container_name: bug_redis
    hostname: redis
    ports: 
      - ${REDIS_PORT_FORWARD}:${REDIS_PORT}
      - ${REDIS_INSIGHT_PORT_FORWARD}:${REDIS_INSIGHT_PORT}
    volumes:
      - bug_redis:/data
    restart: always

volumes:
  bug_pgdata:
    external: true
  bug_redis:
    external: true
