"""empty message

Revision ID: 55b5aceebf12
Revises: 83740233a00d
Create Date: 2022-12-15 19:45:56.436726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55b5aceebf12"
down_revision = "83740233a00d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
